DATA:
  IMAGE_SIZE: 256
  IN_CHANS: 1
  NUM_CLASSES: 0
  MEAN: 0.2817712821212469
  STD: 0.11016652724322151
TRAIN:
  DEBUG: True
  EPOCHS: 300
  WARMUP_EPOCHS: 10
  LR: 2e-3
  MIN_LR: 4e-6
MODEL:
  BACKBONE:
    EMBED_DIM: 24
    MLP_RATIO: 2
    USE_MULTI_MERGE: True
    USE_GHOST_FFN: True
  HEAD:
    OUT_DIM: 768
AUG:
  MULTI_CROP:
    GLOBAL_CROPS_SIZE: 224
    LOCAL_CROPS_SIZE: 96
    LOCAL_CROPS_NUMBER: 8
