from yacs.config import CfgNode

_C = CfgNode()

_C.DATA = CfgNode()
_C.DATA.IMAGE_SIZE = 256
_C.DATA.IN_CHANS = 3
_C.DATA.NUM_CLASSES = 0
_C.DATA.CLASS_FREQ = None
_C.DATA.MEAN = 0.
_C.DATA.STD = 1.

_C.MODEL = CfgNode()
_C.MODEL.TYPE = None
_C.MODEL.EXPANSION_FACTOR = 6

_C.TRAIN = CfgNode()
_C.TRAIN.EPOCHS = 100
_C.TRAIN.WARMUP_EPOCHS = 3
_C.TRAIN.WEIGHT_DECAY = 1e-2
_C.TRAIN.LR = 1e-5
_C.TRAIN.LR_DECAY = 0.1
_C.TRAIN.LR_STEP = 1
_C.TRAIN.LR_SCHEDULER = 'poly'
_C.TRAIN.CLIP_GRAD = 1.0
